config/routes.rb
Rails.application.routes.draw do
  resources :expeditions, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expedition.rb
class Expedition < ApplicationRecord
    validates :name, :description, :length, :difficulty, presence: true

    has_many :expedition_gears
    has_many :gear, through: :expedition_gears
    has_many :reviews

    def gear_attributes=(gear_attributes)
        gear_attributes.each do |attributes|
            if !attributes[:name].empty?
                gear = Gear.find_or_initialize_by(name: attributes[:name])
                if !self.gear.include?(gear)
                    self.gear << gear
                end
            end
        end
    end

    def review_attributes=(review_attributes)
        if review_attributes[:content].empty?
            self.errors.add(:review_content, "must be filled in")
        end

        if review_attributes[:rating] < 1 || review_attributes[:rating] > 5
            self.errors.add(:review_rating, "must be between 1-5")
        end

        if self.errors.messages.empty?
            self.reviews.build(review_attributes)
        end
    end

    def average_rating
        average_rating = self.reviews.average(:rating).to_f.round(1)
        if average_rating < 1
            "This has not yet been rated!"
        else
            average_rating
        end
    end
end

app/models/expedition_gear.rb
class ExpeditionGear < ApplicationRecord
    belongs_to :expedition
    belongs_to :gear
end

app/models/gear.rb
class Gear < ApplicationRecord
    has_many :expedition_gears
    has_many :expeditions, through: :expedition_gears
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :expedition, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/expeditions_controller.rb
class ExpeditionsController < ApplicationController

    def index
        @expeditions = Expedition.all
    end

    def new

    end

    def create
        @expedition = Expedition.new(expedition_params)
        if @expedition.save
            redirect_to expeditions_path
        else
            render :new
        end
    end

    private

    def expedition_params
        params.require(:expedition).permit(:name, :description, :length, :difficulty, gear_attributes: [:name])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expeditions/index.html.erb
<h1>Expeditions</h1>

<% @expeditions.each do |expedition| %>
    <div>
        <h3><%= expedition.name %>
        <h5>Difficulty: <%= expedition.difficulty %> | Length: <%= expedition.length %></h5>
        <h5>Average Rating: <%= expedition.average_rating %></h5>
        <p><%= expedition.description %></p>
        <p>Gear:</p>
        <ul>
            <% expedition.gear.each do |gear| %>
                <li><%= gear.name %></li>
            <% end %>
        </ul>
        <p>Reviews:</p>
        <% expedition.reviews.each do |review| %>
            <div>
                <h5>Rating | <%= review.rating %></h5>
                <p><%= review.content %></p>
            </div>
        <% end %>
    </div>
<% end %>

app/views/expeditions/new.html.erb
<h3>Create a New Expedition</h3>

<form action="/expeditions" method="POST">
    <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token"/>
    <div>
        <label for="expedition_name">Name:</label>
        <div>
            <input type="text" placeholder="Name.." name="expedition[name]"/>
        </div>
    </div>
    <div>
        <label for="expedition_description">Description:</label>
        <div>
            <textarea placeholder="Description..." name="expedition[description]"></textarea>
        </div>
    </div>
    <div>
        <label for="expedition_length">Length:</label>
        <div>
            <input type="number" step="0.01" placeholder="10.5" name="expedition[length]"/>
        </div>
    </div>
    <div>
        <label for="expedition_difficulty">Difficulty:</label>
        <div>
            <input type="text" placeholder="Easy?" name="expedition[difficulty]"/>
        </div>
    </div>
    <div>
        <label for="expedition_gear">Gear:</label>
        <div>
            <div>
                <input type="text" placeholder="Gear Name..." name="expedition[gear_attributes][][name]"/>
            </div>
            <div>
                <input type="text" placeholder="Gear Name..." name="expedition[gear_attributes][][name]"/>
            </div>
            <div>
                <input type="text" placeholder="Gear Name..." name="expedition[gear_attributes][][name]"/>
            </div>
            <div>
                <input type="text" placeholder="Gear Name..." name="expedition[gear_attributes][][name]"/>
            </div>
            <div>
                <input type="text" placeholder="Gear Name..." name="expedition[gear_attributes][][name]"/>
            </div>
        </div>
    </div>
    <input type="submit" value="Add Expedition"/>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedFormsPart1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "View All Expeditions", expeditions_path %>
    <%= link_to "Add New Expedition", new_expedition_path %>

    <%= yield %>
  </body>
</html>